---
title: "title"
author: "Hitesh Khandelwal, Paritosh Panda, Sara Singh"
date: "12/10/2021"
output: html_document
---

# Introduction

## Research Question

# Research Hypothesis

## Loading Libraries
```{r load_libraries}
library(gutenbergr)
library(tidytext)
library(tidyverse)
library(dplyr)
```

## Generating Corpus
```{r corpus, eval=FALSE}
# Generates the initial corpus
# Downloads all Sherlock Holmes books

sherlock_download <- gutenberg_download(c(244, 2097, 2852, 3289, 1661, 834, 108, 2350), mirror="https://gutenberg.pglaf.org/", meta_fields = c("title", "author"))
```

```{r backup, eval=FALSE}
# Backing up and importing data

write_csv(sherlock_download, "sherlock_download.csv") # Downloads a CSV file of the data to maintain a backup.
```

```{r tidy_text}
# Tidying the text
sherlock_import <- read_csv("sherlock_download.csv") # Imports the downloaded CSV file

sherlock_import <- sherlock_import %>%
    mutate(year = case_when(title == "A Study in Scarlet" ~ "1887",
                          title == "The Sign of the Four" ~ "1890",
                          title == "The Hound of the Baskervilles" ~ "1901",
                          title == "The Valley of Fear" ~ "1914",
                          title == "The Adventures of Sherlock Holmes" ~ "1892",
                          title == "The Memoirs of Sherlock Holmes" ~ "1894",
                          title == "The Return of Sherlock Holmes" ~ "1905",
                          title == "His Last Bow: An Epilogue of Sherlock Holmes" ~ "1917")) %>% # Adds the corresponding years to each title
  arrange(year) %>% # Arranging the table by year
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

sherlock_import <- na.omit(sherlock_import) %>% # Removes NA values
  select(-1) #Removes the gutenberg_id column
```

# Corpus Description

# Corpus Summary

# Data Visualization 1

# Data Visualization 2

# Conclusion

# Reflection